config/routes.rb
Sweepstake::Application.routes.draw do

  resources :people, :only => [ :show ]

  get "leaderboards/countries"

  get "leaderboards/people"

  root :to => 'leaderboards#people'
end

app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :bronze, :factor, :gold, :name, :rank, :silver

  before_save :calculate_points

  belongs_to :person

  private

    def calculate_points
      self.points = (self.gold * 10) + (self.silver * 5) + (self.bronze * 3)
      self.total_points = self.points * self.factor
    end
end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :name, :points

  has_many :countries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController
  helper_method :sort_column, :sort_direction

  def countries

    params[:sort] = 'rank' if params[:sort].nil?
    
    if params[:sort] && params[:sort] != 'rank'
      @countries = Country.order(sort_column + " " + sort_direction)
    else
      @not_ranked = Country.where("rank is null")

      if params[:direction] == 'asc' || params[:direction].nil?
        @ranked = Country.where("rank is not null").order("rank ASC")
        @countries = @ranked + @not_ranked
      else
        @ranked = Country.where("rank is not null").order("rank DESC")
        @countries = @not_ranked + @ranked
      end
    end
  end

  def people
    @people = Person.order("points DESC")
  end

  private
  
  def sort_column
    Country.column_names.include?(params[:sort]) ? params[:sort] : "rank"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def show
    @person = Person.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/helpers/leaderboards_helper.rb
module LeaderboardsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>London 2012 Sweepstake</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/leaderboards/countries.html.erb
<h1>London 2012 Sweepstake</h1>
<h2>Country Leaderboard</h2>
<p>
  <%= link_to 'Switch to People leaderboards', leaderboards_people_url, :class => "btn btn-info btn-large" %>
</p>
<p><strong>Points</strong> = <em>(Gold * 10) + (Silver * 5) + (Bronze * 3)</em></p>
<p><strong>Total Points</strong> = <em>Points * Factor</em></p>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th><%= sortable 'rank', 'Medal Rank' %></th>
      <th><%= sortable 'name' %></th>
      <th><%= sortable "gold" %></th>
      <th><%= sortable 'silver' %></th>
      <th><%= sortable 'bronze' %></th>
      <th><%= sortable 'points' %></th>
      <th><%= sortable 'factor' %></th>
      <th><strong><%= sortable 'total_points' %></strong></th>
    <tr>
  </thead>
  <tbody>
  <% @countries.each do |country| %>
    <tr>
      <td><%= country.rank %></td>
      <td><%= country.name %></td>
      <td><%= country.gold %></td>
      <td><%= country.silver %></td>
      <td><%= country.bronze %></td>
      <td><a href="#" rel="tooltip" title="<%= country.points.to_s %>"><%= country.points.truncate(3).to_s %></a></td>
      <td><a href="#" rel="tooltip" title="<%= country.factor.to_s %>"><%= country.factor.truncate(3).to_s %></a></td>
      <td><a href="#" rel="tooltip" title="<%= country.total_points.to_s %>"><strong><%= country.total_points.truncate(3).to_s %></strong></a></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/leaderboards/people.html.erb
<h1>London 2012 Sweepstake</h1>
<h2>People Leaderboard</h2>
<p>
  <%= link_to 'Switch to Country leaderboards', leaderboards_countries_url, :class => "btn btn-info btn-large" %>
<p>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Points</th>
    <tr>
  </thead>
  <tbody>
  <% @people.each do |person| %>
    <tr>
      <td><%= link_to person.name, person_url(person.id) %></td>
      <td><a href="#" rel="tooltip" title="<%= person.points.to_s %>"><strong><%= person.points.truncate(3) %></strong></a></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/people/show.html.erb
<h1>London 2012 Sweepstake</h1>
<h2><%= @person.name %></h2>
<p>
  <%= link_to 'Back to People leaderboards', leaderboards_people_url, :class => "btn btn-info btn-large" %>
</p>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Medal Rank</th>
      <th>Name</th>
      <th>Gold</th>
      <th>Silver</th>
      <th>Bronze</th>
      <th>Points</th>
      <th>Factor</th>
      <th><strong>Total Points</strong></th>
    <tr>
  </thead>
  <tbody>
  <% @person.countries.each do |country| %>
    <tr>
      <td><%= country.rank %></td>
      <td><%= country.name %></td>
      <td><%= country.gold %></td>
      <td><%= country.silver %></td>
      <td><%= country.bronze %></td>
      <td><a href="#" rel="tooltip" title="<%= country.points.to_s %>"><%= country.points.truncate(3).to_s %></a></td>
      <td><a href="#" rel="tooltip" title="<%= country.factor.to_s %>"><%= country.factor.truncate(3).to_s %></a></td>
      <td><a href="#" rel="tooltip" title="<%= country.total_points.to_s %>"><strong><%= country.total_points.truncate(3).to_s %></strong></a></td>
    </tr>
  <% end %>
  </tbody>
</table>